### PR TITLE
Fastlane

### PR DESCRIPTION
**Pull request by IzzySoft**
Fastlane is quite helpful if you want to submit your app to [F-Droid](https://f-droid.org/) – but also for deployment to Play Store (which will probably need the Fastlane binaries): you can maintain summary, description, screenshots and more in one place (you might wish to move your screenshots inside the Fastlane structure as well for that – [my cheat-sheet](https://gitlab.com/snippets/1895688) might be helpful for more details).

### CODE REVIEW

**Comment by NandanDesai** [comment]
Hi! Thanks for you pull request. So, if I just create the rest of the files according to the fastlane folder structure that you have provided, then will that be enough for the app to be added to F-Droid? Can you briefly explain how will this work? I haven't used fastlane and haven't submitted any apps to F-Droid before.

**Comment by IzzySoft** [comment]
What this PR provides is sufficient for F-Droid to enable Fastlane (or rather, to disable the local override otherwise needed, so Fastlane fills in). You can then build on that (e.g. add screenshots), and what you added will be picked up automatically with the next release. Also what you changed (which is the idea behind it: you can keep summary/description in sync with your app's updates without having to notify us each time).

Currently, [your app is in my repo](https://apt.izzysoft.de/fdroid/index/apk/io.nandandesai.privacybreacher). Once this MR is merged, I'd tell my updater to use your Fastlane structure – but other than with F-Droid, I need to tell it explicitly which parts it shall take (so if you later add screenshots, please let me know to enable them as well).

Fastlane is not the only thing needed by F-Droid. Basically, if you agree, you (or I) open an [RFP](https://gitlab.com/fdroid/rfp/issues) (Request For Packaging). The F-Droid issue-bot then will scan your repo to see if your app meets the [inclusion criteria](https://f-droid.org/wiki/page/Inclusion_Policy) (if not, some minor adjustments might be needed – but according to my library scanner, chances look very good). Once that's confirmed, I'd set up metadata (or rather copy them over from my repo; disclosure: I'm also one of the F-Droid maintainers), and one of the packagers initiates the build process (to make sure it works). That last check passed, your app should show up with F-Droid's listings within a week or two.

> I haven't used fastlane

For F-Droid (and for my repo), the presence of the fastlane structure suffices to use it. For Play Store (and maybe other places), you'd also need the Fastlane binaries (which take care for deployment and more). If you don't want to feed Play Store, you won't need those binaries.

> and haven't submitted any apps to F-Droid before

Well, another "first" then? :smiley:

**Comment by NandanDesai** [comment]
Thank you so much for the explanation!! That was awesome!

**Comment by NandanDesai** [comment]
@IzzySoft I've added screenshots as well. Thank you once again!

**Comment by IzzySoft** [comment]
Great! I've updated my configuration accordingly, so all those (short/fulldesc, icon, featureGraphic, screenshots) will be checked and, if changed, updated on each new release detected. Should you need help with the RFP later, let me know (actually, as soon as you open an RFP, I will get to know – as that's where my responsibility as F-Droid maintainer lies :wink:).

**Comment by NandanDesai** [comment]
[Poussinou](https://github.com/Poussinou) said in [this issue](https://github.com/databurn-in/PrivacyBreacher/issues/5#issuecomment-695022620) that they had opened an [RFP](https://gitlab.com/fdroid/rfp/-/issues/1495) for this app.

**Comment by IzzySoft** [comment]
Ah, there is already one – and I've even already commented on it… :blush: OK, then we have just to wait for the next release (for F-Droid, fastlane must be available at the same tag the app is built from). Do you have an ETA for that already?

**Comment by NandanDesai** [comment]
So the app will be available on F-Droid when I make the next release? That is what you mean?

**Comment by IzzySoft** [comment]
I'll trigger the bot again then (to confirm it found Fastlane at the tag), then setup metadata as described above and mark it for our packagers (from there on, see my comment above). But yes, creating a tag covering fastlane would be the next step (feel free to "recycle" the current latest tag for this, as the app itself hasn't changed – i.e. you can delete and re-create the v1.1.1 tag **this time;** please don't do such things with tags F-Droid already has built in the future :wink:).

**Comment by IzzySoft** [comment]
PS: Don't worry, that's just the "initialization process". Once your app is listed, updates just require you to tag releases (and have the tag names matching `versionName` plus increasing `versionCode` accordingly before tagging, of course).

**Comment by NandanDesai** [comment]
Oh cool! Now I get it. Thanks!

**Comment by IzzySoft** [comment]
Just let me know when the tag is there, and I'll kick the RFP upstairs.

**Comment by IzzySoft** [comment]
OK, kicked the bot, thanks!

**Comment by NandanDesai** [comment]
Yes. Done. Please let me know if I've done it as you expected.

**Comment by IzzySoft** [comment]
As you've replied to the RFP, you will get notices from that issue, right? Next two notices to be expected, both within 24h:

* bot confirming
* me preparing metadata and labeling the RFP for our packagers to pick up

If you don't get notifications from there please let me know, and I send you a note here.

**Comment by NandanDesai** [comment]
OK cool! Thank you so much for you help!!

**Comment by IzzySoft** [comment]
All went well so far, according to plan. Now we wait for the packagers…

**Pull request merged**
